version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  default: standard
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: aegis